#!/bin/bash
set -euo pipefail

log()  { printf '[entrypoint] %s\n' "$*"; }
die()  { printf '[entrypoint] ERROR: %s\n' "$*" >&2; exit 1; }

# --- munge -----------------------------------------------------------------
# The key is generated by `apt-get install munge` at build time. Only /run
# needs recreating here, since some container runtimes wipe it.
mkdir -p /run/munge
chown munge:munge /run/munge
gosu munge /usr/sbin/munged

for _ in $(seq 1 20); do
    if munge -n 2>/dev/null | unmunge >/dev/null 2>&1; then break; fi
    sleep 0.2
done
munge -n 2>/dev/null | unmunge >/dev/null 2>&1 \
    || die "munged is not responding; check /var/log/munge/munged.log"
log "munge OK"

# --- slurm.conf -------------------------------------------------------------
# Docker assigns a random hostname per run, and the CPU topology depends on the
# host. `slurmd -C` prints the exact NodeName line slurmd expects, which
# avoids the "Node configuration differs from hardware" error.
HOSTNAME_ACTUAL=$(hostname)
NODELINE=$(/opt/slurm/sbin/slurmd -C 2>/dev/null | head -n1)
[[ "$NODELINE" == NodeName=* ]] || die "slurmd -C returned no NodeName line"

sed -e "s|__NODELINE__|${NODELINE}|" \
    -e "s/__NODENAME__/${HOSTNAME_ACTUAL}/g" \
    /etc/slurm/slurm.conf.template > /etc/slurm/slurm.conf
log "slurm.conf -> ${NODELINE}"

mkdir -p /var/spool/slurmctld /var/spool/slurmd /var/log/slurm /run
chown slurm:slurm /var/spool/slurmctld /var/log/slurm

# --- slurmctld / slurmd -----------------------------------------------------
# Dump the log on failure; otherwise `set -e` kills the container silently.
start_daemon() {
    local bin="$1" logf="$2"
    if ! "$bin"; then
        echo "[entrypoint] ERROR: $bin failed to start. Last lines of $logf:" >&2
        tail -n 40 "$logf" 2>/dev/null || echo "(no log)" >&2
        exit 1
    fi
}

start_daemon /opt/slurm/sbin/slurmctld /var/log/slurm/slurmctld.log
start_daemon /opt/slurm/sbin/slurmd    /var/log/slurm/slurmd.log

for _ in $(seq 1 30); do
    if sinfo -h -o '%T' 2>/dev/null | grep -qv '^unknown'; then break; fi
    sleep 0.5
done

# --- Jupyter ----------------------------------------------------------------
# Runs in the background so the container still gives an interactive shell.
# Log in /var/log/jupyter.log; disable with -e JUPYTER_ENABLE=no.
JUPYTER_ENABLE="${JUPYTER_ENABLE:-yes}"
JUPYTER_PORT="${JUPYTER_PORT:-8888}"
JUPYTER_DIR="${JUPYTER_DIR:-/home/tutorial}"
JUPYTER_TOKEN="${JUPYTER_TOKEN:-cunqa}"

if [[ "$JUPYTER_ENABLE" == "yes" ]]; then
    mkdir -p "$JUPYTER_DIR"
    # --allow-root: the container runs as root and Jupyter refuses by default.
    # ip=0.0.0.0: the default binds to the internal loopback, where -p cannot
    # reach it.
    nohup jupyter notebook \
        --ServerApp.ip=0.0.0.0 \
        --ServerApp.port="$JUPYTER_PORT" \
        --ServerApp.root_dir="$JUPYTER_DIR" \
        --ServerApp.token="$JUPYTER_TOKEN" \
        --ServerApp.open_browser=False \
        --allow-root \
        > /var/log/jupyter.log 2>&1 &

    for _ in $(seq 1 40); do
        if jupyter server list 2>/dev/null | grep -q ":${JUPYTER_PORT}"; then break; fi
        sleep 0.25
    done

    if jupyter server list 2>/dev/null | grep -q ":${JUPYTER_PORT}"; then
        log "Jupyter: http://localhost:${JUPYTER_PORT}/?token=${JUPYTER_TOKEN}"
    else
        log "WARNING: Jupyter did not start. Check /var/log/jupyter.log"
    fi
fi

cat <<'EOF'
====================================================================
Slurm ready. Try: sinfo / srun -N1 hostname / sbatch script.sh

Note: the first job or two may briefly show as "InvalidAccount" in
squeue. That is cosmetic on Slurm >=23.11 without slurmdbd, which is
left out on purpose to keep MySQL out of the image. The job still
runs once the internal cache refreshes (~1 minute the first time).
====================================================================
EOF

# Docker Desktop's Run button gives no TTY, and the default bash would read
# EOF and exit, stopping the container. Keep it alive and stream the Jupyter
# log instead, so the Logs tab shows something useful. An explicit command
# (docker run ... bash, docker exec) is unaffected.
if [[ $# -eq 1 && "$1" == "/bin/bash" && ! -t 0 ]]; then
    log "No TTY: staying up. Use the Jupyter terminal, or docker exec -it <name> bash"
    exec tail -f /var/log/jupyter.log
fi

exec "$@"
